import type { Metadata } from "next";
import { Bricolage_Grotesque } from "next/font/google";
import "./globals.css";

const bricolageGrotesque = Bricolage_Grotesque({
  subsets: ["latin"],
  variable: "--font-bricolage",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      className={`${bricolageGrotesque.variable} h-full antialiased`}
      lang="en"
      style={{ fontFamily: "var(--font-bricolage)" }}
    >
      <body className="flex min-h-full flex-col">{children}</body>
    </html>
  );
}
